_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.6
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.6
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
arch:
    value: fc1
learning_rate:
    value: 0.0012
prune_iter:
    value: 35
prune_percent:
    value: 51
